local _, HG = ...

HG:RegisterTab("character", "CHARACTER", 2, function(parent)
    local level = HG:Section(parent, "LEVEL & CHARACTER", 12, -12, 736, 124)
    HG:Label(level, "Level", 14, -50)
    local levelField = HG:Edit(level, "level", 76, -41, 72, true, UnitLevel("player") or 1)
    HG:Step(level, levelField, "-", 158, -41, -1, 1, 120)
    HG:Step(level, levelField, "+", 196, -41, 1, 1, 120)
    HG:Button(level, "SET LEVEL", 234, -41, 100, function()
        local desired = HG:GetPositiveInteger("level", "level", 120)
        if not desired then return end
        local difference = desired - UnitLevel("player")
        if difference == 0 then HG:Notify("You are already level " .. desired .. ".") return end
        HG:Execute("level", difference)
    end)
    local characterActions = {}
    characterActions[#characterActions + 1] = HG:Button(level, "RESET TALENTS", 0, -75, 112, function()
        HG:ExecuteConfirmed("resetTalents", "Reset talents for the selected character?")
    end)
    characterActions[#characterActions + 1] = HG:Button(level, "CUSTOMIZE", 0, -75, 94, function()
        HG:ExecuteConfirmed("customize", "Flag the selected character for appearance customization?")
    end, "Flags the selected character for a full appearance customization at next login.")
    characterActions[#characterActions + 1] = HG:Button(level, "RENAME", 0, -75, 78, function()
        HG:ExecuteConfirmed("rename", "Flag the selected character for rename?")
    end, "Flags only the selected character's name for change at next login.")
    characterActions[#characterActions + 1] = HG:Button(level, "RACE", 0, -75, 72, function()
        HG:ExecuteConfirmed("changeRace", "Flag the selected character for a race change?")
    end)
    characterActions[#characterActions + 1] = HG:Button(level, "FACTION", 0, -75, 84, function()
        HG:ExecuteConfirmed("changeFaction", "Flag the selected character for a faction change?")
    end)
    characterActions[#characterActions + 1] = HG:Button(level, "LANGUAGES", 0, -75, 96, function() HG:Execute("learnLanguages") end)
    HG:AlignRow(level, characterActions, 76, -85, 10)

    local items = HG:Section(parent, "ITEMS", 12, -146, 736, 124)
    HG:Label(items, "Search", 14, -50)
    local itemSearch = HG:Edit(items, "itemSearch", 76, -41, 180, false, "")
    HG:ClearButton(items, itemSearch, 266, -41)
    HG:Button(items, "SEARCH", 304, -41, 82, function()
        local query = strtrim(itemSearch:GetText() or "")
        if query == "" then HG:Notify("Enter an item name or ID.") return end
        HG:OpenLookupModal("lookupItem", query, "itemID", "ITEMS")
    end)
    HG:Label(items, "Item ID", 14, -94)
    local itemID = HG:Edit(items, "itemID", 76, -85, 90, true, "")
    HG:ClearButton(items, itemID, 176, -85)
    HG:Label(items, "Qty", 214, -94)
    local qty = HG:Edit(items, "itemQty", 246, -85, 52, true, "1")
    HG:Step(items, qty, "-", 308, -85, -1, 1, 999)
    HG:Step(items, qty, "+", 346, -85, 1, 1, 999)
    HG:Button(items, "ADD", 384, -85, 76, function()
        local id = HG:GetPositiveInteger("itemID", "item ID")
        local count = HG:GetPositiveInteger("itemQty", "quantity", 999)
        if id and count then HG:Execute("addItem", id, count) end
    end)
    HG:Button(items, "REMOVE", 470, -85, 86, function()
        local id = HG:GetPositiveInteger("itemID", "item ID")
        local count = HG:GetPositiveInteger("itemQty", "quantity", 999)
        if id and count then HG:Execute("removeItem", id, count) end
    end)
    local spells = HG:Section(parent, "SPELLS", 12, -280, 736, 124)
    HG:Label(spells, "Search", 14, -50)
    local spellSearch = HG:Edit(spells, "spellSearch", 76, -41, 180, false, "")
    HG:ClearButton(spells, spellSearch, 266, -41)
    HG:Button(spells, "SEARCH", 304, -41, 82, function()
        local query = strtrim(spellSearch:GetText() or "")
        if query == "" then HG:Notify("Enter a spell name or ID.") return end
        HG:OpenLookupModal("lookupSpell", query, "spellID", "SPELLS")
    end)
    HG:Label(spells, "Spell ID", 14, -94)
    local spellID = HG:Edit(spells, "spellID", 76, -85, 90, true, "")
    HG:ClearButton(spells, spellID, 176, -85)
    HG:Button(spells, "LEARN SELF/TARGET", 214, -85, 136, function()
        local id = HG:GetPositiveInteger("spellID", "spell ID")
        if id then HG:Execute("learn", id) end
    end, "Learns on a selected player, or yourself when no player is selected.")
    HG:Button(spells, "UNLEARN TARGET", 360, -85, 126, function()
        local id = HG:GetPositiveInteger("spellID", "spell ID")
        if id then HG:Execute("unlearn", id) end
    end, "HavenCore requires a selected player for Unlearn.")
    HG:Button(spells, "CAST SELF", 496, -85, 96, function()
        local id = HG:GetPositiveInteger("spellID", "spell ID")
        if id then HG:Execute("castSelf", id) end
    end)
    HG:Button(spells, "CAST TARGET", 602, -85, 110, function()
        local id = HG:GetPositiveInteger("spellID", "spell ID")
        if id then HG:Execute("castTarget", id) end
    end)

end)
