local _, HG = ...

HG:RegisterTab("character", "CHARACTER", 2, function(parent)
    local level = HG:Section(parent, "LEVEL & CHARACTER", 12, -12, 736, 116)
    HG:Label(level, "Level", 14, -46)
    local levelField = HG:Edit(level, "level", 58, -37, 72, true, UnitLevel("player") or 1)
    HG:Step(level, levelField, "-", 140, -37, -1, 1, 120)
    HG:Step(level, levelField, "+", 174, -37, 1, 1, 120)
    HG:Button(level, "SET LEVEL", 214, -37, 100, function()
        local desired = HG:GetPositiveInteger("level", "level", 120)
        if not desired then return end
        local difference = desired - UnitLevel("player")
        if difference == 0 then HG:Notify("You are already level " .. desired .. ".") return end
        HG:Execute("level", difference)
    end)
    HG:Button(level, "RESET TALENTS", 14, -75, 112, function()
        HG:ExecuteConfirmed("resetTalents", "Reset talents for the selected character?")
    end)
    HG:Button(level, "CUSTOMIZE", 136, -75, 94, function()
        HG:ExecuteConfirmed("customize", "Flag the selected character for appearance customization?")
    end, "Flags the selected character for a full appearance customization at next login.")
    HG:Button(level, "RENAME", 240, -75, 78, function()
        HG:ExecuteConfirmed("rename", "Flag the selected character for rename?")
    end, "Flags only the selected character's name for change at next login.")
    HG:Button(level, "RACE", 328, -75, 72, function()
        HG:ExecuteConfirmed("changeRace", "Flag the selected character for a race change?")
    end)
    HG:Button(level, "FACTION", 410, -75, 84, function()
        HG:ExecuteConfirmed("changeFaction", "Flag the selected character for a faction change?")
    end)
    HG:Button(level, "LANGUAGES", 504, -75, 96, function() HG:Execute("learnLanguages") end)

    local items = HG:Section(parent, "ITEMS", 12, -140, 736, 98)
    HG:Label(items, "Search", 14, -44)
    local itemSearch = HG:Edit(items, "itemSearch", 66, -35, 180, false, "")
    HG:ClearButton(items, itemSearch, 252, -35)
    HG:Button(items, "SEARCH", 286, -35, 82, function()
        local query = strtrim(itemSearch:GetText() or "")
        if query == "" then HG:Notify("Enter an item name or ID.") return end
        HG:OpenLookupModal("lookupItem", query, "itemID", "ITEMS")
    end)
    HG:Label(items, "Item ID", 14, -78)
    HG:Edit(items, "itemID", 66, -69, 90, true, "")
    HG:Label(items, "Qty", 170, -78)
    local qty = HG:Edit(items, "itemQty", 202, -69, 52, true, "1")
    HG:Step(items, qty, "-", 264, -69, -1, 1, 999)
    HG:Step(items, qty, "+", 298, -69, 1, 1, 999)
    HG:Button(items, "ADD", 342, -69, 76, function()
        local id = HG:GetPositiveInteger("itemID", "item ID")
        local count = HG:GetPositiveInteger("itemQty", "quantity", 999)
        if id and count then HG:Execute("addItem", id, count) end
    end)
    HG:Button(items, "REMOVE", 428, -69, 86, function()
        local id = HG:GetPositiveInteger("itemID", "item ID")
        local count = HG:GetPositiveInteger("itemQty", "quantity", 999)
        if id and count then HG:Execute("removeItem", id, count) end
    end)
    HG:Label(items, "Ctrl + Right-click a bag item to load its ID.", 530, -76, 190)

    local spells = HG:Section(parent, "SPELLS", 12, -250, 736, 98)
    HG:Label(spells, "Search", 14, -44)
    local spellSearch = HG:Edit(spells, "spellSearch", 66, -35, 180, false, "")
    HG:ClearButton(spells, spellSearch, 252, -35)
    HG:Button(spells, "SEARCH", 286, -35, 82, function()
        local query = strtrim(spellSearch:GetText() or "")
        if query == "" then HG:Notify("Enter a spell name or ID.") return end
        HG:OpenLookupModal("lookupSpell", query, "spellID", "SPELLS")
    end)
    HG:Label(spells, "Spell ID", 14, -78)
    HG:Edit(spells, "spellID", 76, -69, 90, true, "")
    HG:Button(spells, "LEARN SELF/TARGET", 176, -69, 136, function()
        local id = HG:GetPositiveInteger("spellID", "spell ID")
        if id then HG:Execute("learn", id) end
    end, "Learns on a selected player, or yourself when no player is selected.")
    HG:Button(spells, "UNLEARN TARGET", 322, -69, 126, function()
        local id = HG:GetPositiveInteger("spellID", "spell ID")
        if id then HG:Execute("unlearn", id) end
    end, "HavenCore requires a selected player for Unlearn.")
    HG:Button(spells, "CAST SELF", 458, -69, 96, function()
        local id = HG:GetPositiveInteger("spellID", "spell ID")
        if id then HG:Execute("castSelf", id) end
    end)
    HG:Button(spells, "CAST TARGET", 564, -69, 110, function()
        local id = HG:GetPositiveInteger("spellID", "spell ID")
        if id then HG:Execute("castTarget", id) end
    end)

    local morph = HG:Section(parent, "MORPH — ADVANCED DISPLAY ID", 12, -360, 736, 62)
    HG:Label(morph, "Display ID", 14, -44)
    HG:Edit(morph, "morphID", 84, -35, 80, true, "")
    HG:Button(morph, "MORPH", 174, -35, 76, function()
        local id = HG:GetPositiveInteger("morphID", "display ID")
        if id then HG:Execute("morph", id) end
    end, "Morph expects a creature Display ID, not an NPC entry or animation ID. Use Debug > NPC Info to discover one.")
    HG:Button(morph, "CLEAR", 260, -35, 68, function() HG:Execute("demorph") end)
    HG:Label(morph, "Use Debug > NPC Info to find a target creature's DisplayID.", 344, -42, 360)
end)
